apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- service.yaml
patches:
# remove --autogenerate-certificate option & add custom certificate paths
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1/secret/secretName
      value: dex.philiprumman.com-tls