apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- github-secret.yaml
patchesStrategicMerge:
- service.yaml
patches:
# replace default tls certificate name with new secret, reflected from orgin-ca-issuer
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1/secret/secretName
      value: philiprumman.com-tls
  target:
    kind: Deployment
    name: dex
- patch: |-
    - op: replace
      path: /data/config.yaml
      value: |
        issuer: https://dex.example.com:32000
        storage:
          type: kubernetes
          config:
            inCluster: true
        web:
          https: 0.0.0.0:5556
          tlsCert: /etc/dex/tls/tls.crt
          tlsKey: /etc/dex/tls/tls.key
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            redirectURI: https://dex.philiprumman.com/callback
            org: kubernetes
        oauth2:
          skipApprovalScreen: true

        staticClients:
        - id: example-app
          redirectURIs:
          - 'http://127.0.0.1:5555/callback'
          name: 'Example App'
          secret: ZXhhbXBsZS1hcHAtc2VjcmV0

        enablePasswordDB: true
        staticPasswords:
        - email: "admin@example.com"
          # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          username: "admin"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  target:
    kind: ConfigMap
    name: dex

    