apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- github-secret.yaml
patchesStrategicMerge:
- service.yaml
patches:
# replace default tls certificate name with new secret, reflected from orgin-ca-issuer
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1/secret/secretName
      value: philiprumman.com-tls
  target:
    kind: Deployment
    name: dex
- patch: |-
    - op: replace
      path: /data/connectors/1/config/redirectURI
      value: https://dex.philiprumman.com/callback
  target:
    kind: ConfigMap
    name: dex

    