apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- dex.philiprumman.com-tls.yaml
- ingress.yaml
patchesStrategicMerge:
- service.yaml
patches:
# replace default tls certificate name with new secret
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1/secret/secretName
      value: dex.philiprumman.com-tls
  target:
    kind: Deployment
    name: dex