apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: philiprumman.com
  namespace: origin-ca-issuer
spec:
  secretTemplate:
    annotations:
      my-secret-annotation-1: "foo"
      my-secret-annotation-2: "bar"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,cert-manager,kubernetes-dashboard,dex"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cert-manager,kubernetes-dashboard,dex"
    labels:
      my-secret-label: foo
  # The secret name where cert-manager
  # should store the signed certificate.
  secretName: philiprumman.com-tls
  dnsNames:
    - "philiprumman.com"
    - "*.philiprumman.com"
  # Duration of the certificate.
  duration: 168h0m0s
  # Renew a day before the certificate expiration.
  renewBefore: 24h0m0s
  # Reference the Origin CA Issuer you created above,
  # which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer
