apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ingress-nginx-controller"
spec:
  template:
    spec:
      containers:
        - name: controller 
          imagePullPolicy: never
          #args:
          #  - "--enable-ssl-passthrough"
