kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/cloud/deploy.yaml
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-ssl-passthrough
  target:
    kind: Deployment
